#!/bin/sh

# go to last dir on yazi exit, Q to keep the same dir
yz() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	command rm -f -- "$tmp" # `command` to ignore alias
}

# go to last dir on lf exit
lfcd() {
	cd "$(command lf -print-last-dir "$@")"
}
alias lf="COLORTERM=truecolor lfcd" # lf doesn't detact truecolor in ssh session

alias rm="rm -Ivr"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias cp="cp -rv"
alias scp="scp -r"
alias df="df -h"
alias du="du -h"
alias rsync="rsync -uPrv"
alias dd="dd status=progress"
alias ffmpeg="ffmpeg -hide_banner" # hide build flags

# color
alias grep="grep --color=always"
alias ls="ls -h --color=always"
alias diff="diff --color=always"

alias doas="doas " # this make doas uses user alias, don't know how this works

alias plop="doas qlop"
alias goOutside="doas emerge -avuDN @world --keep-going"
alias yeet="doas pacman -Rns"
alias goodnight="shutdown -h now"

alias mpnv="mpv --no-video --directory-mode=recursive"
alias vi="nvim"
alias myconfig="git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME"
alias etcport="git --git-dir=$HOME/.config/.etc-portage --work-tree=/etc/portage"

# https://github.com/occivink/mpv-image-viewer
alias mpi="mpv --config-dir=$HOME/.config/mpi"

# change nmtui color with NEWT_COLORS; can also do NEWT_MONO=1
command -v nmtui >/dev/null 2>&1 &&
	nmtui_color="$XDG_CONFIG_HOME/newt/transparent_nmtui"
	for i in "nmtui" "nmtui-edit" "nmtui-connect" "nmtui-hostname"; do
		# duct tape
		alias "$i"="NEWT_COLORS_FILE=$nmtui_color NMT_NEWT_COLORS_FILE=$nmtui_color $i"
	done
