#! /bin/sh

alias grep="grep --color=always"
alias ls="ls --color=always"
alias rm="rm -Ivr"
alias mkdir="mkdir -pv"
alias mv="mv -iv"
alias cp="cp -rv"
alias scp="scp -r"
alias df="df -h"
alias du="du -h"

alias yeet="doas pacman -Rns"
alias goodnight="shutdown -h now"

alias lf=lfcd
alias mpv="mpv --terminal=no"
alias mpnv="mpv --terminal=yes --no-video"
alias vi="nvim"
alias myconfig="git --git-dir=$HOME/.dotfiles --work-tree=$HOME"
