#!/bin/sh

genThumbnail(){ # {{{
	# just copied from yazi lmao
	# https://github.com/sxyazi/yazi/blob/main/yazi-plugin/preset/plugins/video.lua
	vduration=$(ffprobe -i "$1" -show_entries format=duration -v quiet -of csv="p=0")
	removedecimal=$(printf "%.0f\n" "$vduration")
	percentage=5
	quality=2 # -q:v parameter (2:31); smaller is better
	pointToJump=$(((removedecimal * percentage) / 100))
	width=350

	ffmpeg -v quiet -threads 1 -hwaccel auto \
		-skip_frame nokey -ss "$pointToJump" \
		-an -sn -dn -i "$1" \
		-map 0:v -vframes 1 -q:v $quality \
		-vf "scale=-1:'min($width,ih)':flags=fast_bilinear" \
		-f image2 "$THUMB_CACHE"
		#-f image2 pipe:1
} # }}}

case "$(file -Lb --mime-type -- "$1")" in

	image/*) # {{{
		chafa -f sixel -s "$2x$3" --animate off --polite on "$1" || echo "failed to preview image"
		# exit 0 will cache sixel in memory
		exit 1;; # }}}

	video/*) # {{{
		CACHE_DIR="/tmp/lf-preview/"
		[ -d $CACHE_DIR ] || mkdir -p $CACHE_DIR
		THUMB_CACHE="$CACHE_DIR/$(sha256sum "$1" | cut -d' ' -f1)"

		# TODO: chafa is broken here sometimes, img2sixel doesn't have that problem
		if [ -f "$THUMB_CACHE" ]; then
			chafa "$THUMB_CACHE" || echo "failed to preview video"
		else
			genThumbnail "$1" && chafa "$THUMB_CACHE" || echo "failed to preview video"
		fi
		exit 1;; # }}}

	audio/*) # {{{
		exiftool "$1"
		;; # }}}

	application/json) # {{{
		jq --color-output . "$1" || cat "$1"
		;; # }}}

	application/zip) # {{{
		zipinfo -1 "$1"
		;; # }}}

	application/x-7z-compressed|application/vnd.rar) # {{{
		# https://stackoverflow.com/questions/55355466/7z-list-only-filenames
		# there is no 7z documentaton so its just great
		7z l -ba "$1" | grep -vF 'D....' | grep -oP '(?<=^.{53}).*'
		;; # }}}

	*/x-tar|*/x-xz|*/zstd|*/gzip|*/x-bzip2) # {{{
		tar -tf "$1"
		;; # }}}

	application/*executable) # {{{
		file -bL "$1" | tr ',' '\n'
		;; # }}}

	text/*) # {{{
		cat "$1"
		;; # }}}

	*) # {{{
		file -Lb --mime-type -- "$1"
		;; # }}}
esac

# vim:fdm=marker
