#!/bin/sh

### disable time out
#xset -dpms
#xset s off

### startup program
feh --bg-fill --no-fehbg "$XDG_DATA_HOME/wallpaper"
picom &
kmonad "$XDG_CONFIG_HOME/kmonad/swapAltAndMeta.kbd" &
kdeconnectd &
redshift &
dunst &

### start wm, only one exec in last
exec dwm # muh LOC
#exec i3
