import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM= "xterm-256color"

[font]
normal = { family = "Maple Mono", style = "Regular"}
size = 12

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Underline"
blinking = "Always"

[window]
#decorations = "None"
padding               = { x = 9, y = 9 }
opacity               = 0.5
#blur = true
#decorations_theme_varient = "Dark"

[colors]
transparent_background_colors = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{key="Return",mods="Super|Shift",action="SpawnNewInstance"},
]
