[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
normal = { family = "monospace", style = "Regular"}
size = 12

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Underline"
blinking = "Always"

[window]
padding               = { x = 9, y = 9 }
opacity               = 0.5

[colors]
transparent_background_colors = false # transparency for cell background

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
	{key="Return",mods="Super|Shift",action="SpawnNewInstance"},
	{key="i",mods="Control",action="ScrollPageUp"},
	{key="e",mods="Control",action="ScrollPageDown"},
]
