import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM= "xterm-256color"

[font]
normal = { family = "Maple Mono", style = "Regular"}
size = 12

[cursor.style]
shape = "Underline"
blinking = "Always"

[window]

#decorations = "None"
padding               = { x = 5, y = 5 }
opacity               = 0.8
blur = true
